// Fallback localization for PF2e Weather Forge.
// This is intentionally kept in sync with lang/de.json and lang/en.json so the module remains usable if Foundry does not load package language files.
export const WEATHER_FORGE_TRANSLATIONS = {
  "de": {
    "pf2e-weather-forge.app.title": "PF2e Wetter Forge",
    "pf2e-weather-forge.chat.defaultMode": "Standard-Chat-Ausgabe",
    "pf2e-weather-forge.chat.mode.ask": "Beim Veröffentlichen nachfragen",
    "pf2e-weather-forge.chat.mode.gm": "Whisper an GM",
    "pf2e-weather-forge.chat.mode.public": "Öffentlich",
    "pf2e-weather-forge.chat.publishGM": "An GM senden",
    "pf2e-weather-forge.chat.publishPublic": "Öffentlich senden",
    "pf2e-weather-forge.chat.publishTitle": "Wetter veröffentlichen",
    "pf2e-weather-forge.chat.speaker": "PF2e Wetter Forge",
    "pf2e-weather-forge.chat.title": "Wetterbericht",
    "pf2e-weather-forge.climate.arctic": "Arktisch",
    "pf2e-weather-forge.climate.coastal": "Küste",
    "pf2e-weather-forge.climate.desert": "Wüste",
    "pf2e-weather-forge.climate.magical": "Magisch verzerrt",
    "pf2e-weather-forge.climate.mediterranean": "Mediterran",
    "pf2e-weather-forge.climate.mountain": "Gebirge",
    "pf2e-weather-forge.climate.swamp": "Sumpf",
    "pf2e-weather-forge.climate.temperate": "Gemäßigt",
    "pf2e-weather-forge.climate.tropical": "Tropisch",
    "pf2e-weather-forge.cloudDensity.clear": "klar",
    "pf2e-weather-forge.cloudDensity.cloudy": "bewölkt",
    "pf2e-weather-forge.cloudDensity.overcast": "bedeckt",
    "pf2e-weather-forge.cloudDensity.scattered": "locker bewölkt",
    "pf2e-weather-forge.description.clearMild": "Die Luft ist ruhig und angenehm. Ein brauchbarer Reisetag, ohne Launen des Himmels.",
    "pf2e-weather-forge.description.coldClear": "Die Luft ist klar und kalt. Jeder Atemzug steht kurz sichtbar in der Welt, bevor er verschwindet.",
    "pf2e-weather-forge.description.extreme.blizzard": "Schnee und Wind verschmelzen zu weißem Tosen. Orientierung wird zum Würfelwurf gegen den Himmel.",
    "pf2e-weather-forge.description.extreme.coldSnap": "Eine harte Kälte hat sich festgebissen. Finger werden steif, Atem brennt und selbst Geräusche wirken spröde.",
    "pf2e-weather-forge.description.extreme.fog": "Dichter Nebel verschluckt Entfernung und Form. Die Welt endet wenige Schritte voraus.",
    "pf2e-weather-forge.description.extreme.heatwave": "Die Hitze steht wie Glas in der Luft. Jede Bewegung kostet mehr Kraft als sie sollte.",
    "pf2e-weather-forge.description.extreme.storm": "Ein Sturm herrscht über die Gegend. Böen reißen an allem, Regen schlägt schräg und der Himmel wirkt wie ein wütendes Tier.",
    "pf2e-weather-forge.description.heavyRain": "Regen prasselt schwer herab. Pfützen wachsen schnell, Stoff klebt an Haut und Rüstung klingt dumpf unter den Tropfen.",
    "pf2e-weather-forge.description.hotClear": "Hitze liegt schwer über der Landschaft. Metall wird unangenehm warm und Schatten fühlen sich kostbar an.",
    "pf2e-weather-forge.description.lightRain": "Feiner Regen legt sich auf Kleidung und Wege. Die Welt wirkt gedämpft, als hätte jemand eine nasse Decke über die Geräusche gelegt.",
    "pf2e-weather-forge.description.mist": "Feuchter Dunst hängt bodennah in der Luft und verschluckt Geräusche wie nasser Filz.",
    "pf2e-weather-forge.description.overcast": "Eine dichte Wolkendecke hängt über der Gegend. Das Licht ist flach, die Stimmung geduckt.",
    "pf2e-weather-forge.description.snow": "Schnee fällt in kalten Schleiern. Schritte werden leiser, Konturen weicher und die Luft beißt in jeder Atempause.",
    "pf2e-weather-forge.description.thunderstorm": "Schwere Wolken türmen sich auf, Donner rollt über die Landschaft und Regen peitscht in Böen herab.",
    "pf2e-weather-forge.description.windy": "Der Wind zerrt an Mänteln, Haaren und losen Riemen. Gespräche müssen gegen das Heulen der Böen ankämpfen.",
    "pf2e-weather-forge.extreme.blizzard": "Schneesturm",
    "pf2e-weather-forge.extreme.coldSnap": "Kälteeinbruch",
    "pf2e-weather-forge.extreme.fog": "Dichter Nebel",
    "pf2e-weather-forge.extreme.heatwave": "Hitzewelle",
    "pf2e-weather-forge.extreme.none": "Keine",
    "pf2e-weather-forge.extreme.storm": "Sturm",
    "pf2e-weather-forge.extremePhase.active": "aktiv",
    "pf2e-weather-forge.extremePhase.building": "zieht auf",
    "pf2e-weather-forge.extremePhase.fading": "klingt ab",
    "pf2e-weather-forge.field.climateZone": "Klimazone",
    "pf2e-weather-forge.field.cloudDensity": "Wolkendichte",
    "pf2e-weather-forge.field.dailyMinMax": "Tagesminimum/-maximum",
    "pf2e-weather-forge.field.dayOfMonth": "Tag des Monats",
    "pf2e-weather-forge.field.extremeWeather": "Extremwetter",
    "pf2e-weather-forge.field.humidity": "Luftfeuchtigkeit",
    "pf2e-weather-forge.field.month": "Monat",
    "pf2e-weather-forge.field.moonPhase": "Mondphase",
    "pf2e-weather-forge.field.precipitation": "Niederschlag",
    "pf2e-weather-forge.field.temperature": "Temperatur",
    "pf2e-weather-forge.field.timeSegment": "Tageszeit",
    "pf2e-weather-forge.field.trend": "Trend",
    "pf2e-weather-forge.field.weekday": "Wochentag",
    "pf2e-weather-forge.field.windStrength": "Windstärke",
    "pf2e-weather-forge.field.year": "Jahr",
    "pf2e-weather-forge.history.clear": "Historie leeren",
    "pf2e-weather-forge.history.empty": "Noch keine Wetterhistorie vorhanden. Übernimm eine Vorschau, um den ersten Eintrag zu speichern.",
    "pf2e-weather-forge.history.hint": "Speichert jedes übernommene Wetter nach Datum und Tageszeit. Die Einträge bleiben vollständig lokalisierbar, da intern Schlüssel statt fertiger Texte gespeichert werden.",
    "pf2e-weather-forge.history.noEntries": "Keine Einträge",
    "pf2e-weather-forge.history.title": "Wetterhistorie",
    "pf2e-weather-forge.humidity.dry": "trocken",
    "pf2e-weather-forge.humidity.humid": "feucht",
    "pf2e-weather-forge.humidity.normal": "normal",
    "pf2e-weather-forge.humidity.veryHumid": "sehr feucht",
    "pf2e-weather-forge.month.abadius": "Abadius (Januar)",
    "pf2e-weather-forge.month.arodus": "Arodus (August)",
    "pf2e-weather-forge.month.calistril": "Calistril (Februar)",
    "pf2e-weather-forge.month.desnus": "Desnus (Mai)",
    "pf2e-weather-forge.month.erastus": "Erastus (Juli)",
    "pf2e-weather-forge.month.gozran": "Gozran (April)",
    "pf2e-weather-forge.month.kuthona": "Kuthona (Dezember)",
    "pf2e-weather-forge.month.lamashan": "Lamashan (Oktober)",
    "pf2e-weather-forge.month.neth": "Neth (November)",
    "pf2e-weather-forge.month.pharast": "Pharast (März)",
    "pf2e-weather-forge.month.rova": "Rova (September)",
    "pf2e-weather-forge.month.sarenith": "Sarenith (Juni)",
    "pf2e-weather-forge.moon.firstQuarter": "Erstes Viertel",
    "pf2e-weather-forge.moon.full": "Vollmond",
    "pf2e-weather-forge.moon.fullMoon": "Vollmond",
    "pf2e-weather-forge.moon.lastQuarter": "Letztes Viertel",
    "pf2e-weather-forge.moon.new": "Neumond",
    "pf2e-weather-forge.moon.newMoon": "Neumond",
    "pf2e-weather-forge.moon.waningCrescent": "Abnehmende Sichel",
    "pf2e-weather-forge.moon.waningGibbous": "Abnehmender Mond",
    "pf2e-weather-forge.moon.waxingCrescent": "Zunehmende Sichel",
    "pf2e-weather-forge.moon.waxingGibbous": "Zunehmender Mond",
    "pf2e-weather-forge.notification.calendarSaved": "Der interne Kalender wurde gespeichert.",
    "pf2e-weather-forge.notification.historyCleared": "Die Wetterhistorie wurde geleert.",
    "pf2e-weather-forge.notification.settingsSaved": "Einstellungen gespeichert.",
    "pf2e-weather-forge.notification.weatherAccepted": "Die Wettervorschau wurde übernommen.",
    "pf2e-weather-forge.notification.weatherReset": "Das Wetter wurde für die gewählte Klimazone zurückgesetzt.",
    "pf2e-weather-forge.precipitation.drizzle": "Nieselregen",
    "pf2e-weather-forge.precipitation.heavyRain": "Starker Regen",
    "pf2e-weather-forge.precipitation.lightRain": "Leichter Regen",
    "pf2e-weather-forge.precipitation.mist": "Nebel/Dunst",
    "pf2e-weather-forge.precipitation.none": "Kein Niederschlag",
    "pf2e-weather-forge.precipitation.rain": "Regen",
    "pf2e-weather-forge.precipitation.snow": "Schnee",
    "pf2e-weather-forge.precipitation.thunderstorm": "Gewitter",
    "pf2e-weather-forge.season.autumn": "Herbst",
    "pf2e-weather-forge.season.spring": "Frühling",
    "pf2e-weather-forge.season.summer": "Sommer",
    "pf2e-weather-forge.season.winter": "Winter",
    "pf2e-weather-forge.settings.allowExtreme.hint": "Legt fest, ob Extremwetter bei der Generierung zufällig auftreten darf.",
    "pf2e-weather-forge.settings.allowExtreme.name": "Extremwetter erlauben",
    "pf2e-weather-forge.settings.calendarState.hint": "Speichert den internen Golarion-Kalender der Wetter Forge.",
    "pf2e-weather-forge.settings.calendarState.name": "Kalenderzustand",
    "pf2e-weather-forge.settings.chatOutputMode.hint": "Legt fest, welcher Chat-Ausgabemodus im Wetterfenster vorausgewählt wird.",
    "pf2e-weather-forge.settings.chatOutputMode.name": "Chat-Ausgabemodus",
    "pf2e-weather-forge.settings.extremeFrequency.name": "Extremwetter-Häufigkeit",
    "pf2e-weather-forge.settings.extremeFrequency.hint": "Legt fest, wie häufig Extremwetter zufällig entstehen kann.",
    "pf2e-weather-forge.settings.extremeFrequency.rare": "Selten",
    "pf2e-weather-forge.settings.extremeFrequency.normal": "Normal",
    "pf2e-weather-forge.settings.extremeFrequency.frequent": "Häufig",
    "pf2e-weather-forge.settings.extremeFrequency.veryFrequent": "Sehr häufig",
    "pf2e-weather-forge.settings.historyLimit.180": "180 Tage",
    "pf2e-weather-forge.settings.historyLimit.30": "30 Tage",
    "pf2e-weather-forge.settings.historyLimit.365": "365 Tage",
    "pf2e-weather-forge.settings.historyLimit.90": "90 Tage",
    "pf2e-weather-forge.settings.historyLimit.hint": "Legt fest, wie viele Kalendertage in der Wetterhistorie erhalten bleiben.",
    "pf2e-weather-forge.settings.historyLimit.name": "Historienlimit",
    "pf2e-weather-forge.settings.historyLimit.unlimited": "Unbegrenzt",
    "pf2e-weather-forge.settings.open.hint": "Öffnet die PF2e Wetter Forge.",
    "pf2e-weather-forge.settings.open.label": "Öffnen",
    "pf2e-weather-forge.settings.open.name": "Wetter Forge öffnen",
    "pf2e-weather-forge.settings.weatherHistory.hint": "Speichert die übernommenen Wetterlagen für spätere Nachverfolgung.",
    "pf2e-weather-forge.settings.weatherHistory.name": "Wetterhistorie",
    "pf2e-weather-forge.settings.weatherPreview.hint": "Speichert die aktuelle Vorschau, bevor sie übernommen wird.",
    "pf2e-weather-forge.settings.weatherPreview.name": "Wettervorschau",
    "pf2e-weather-forge.settings.weatherState.hint": "Speichert das aktuelle Wetter der Welt.",
    "pf2e-weather-forge.settings.weatherState.name": "Wetterzustand",
    "pf2e-weather-forge.settingsTab.calendarTitle": "Kalender",
    "pf2e-weather-forge.settingsTab.climateTitle": "Klima & Extremwetter",
    "pf2e-weather-forge.settingsTab.outputTitle": "Historie & Chat",
    "pf2e-weather-forge.settingsTab.save": "Einstellungen speichern",
    "pf2e-weather-forge.tabs.generator": "Wettergenerierung",
    "pf2e-weather-forge.tabs.history": "Wetterhistorie",
    "pf2e-weather-forge.tabs.label": "PF2e Weather Forge Reiter",
    "pf2e-weather-forge.tabs.settings": "Einstellungen",
    "pf2e-weather-forge.time.afternoon": "Nachmittags",
    "pf2e-weather-forge.time.evening": "Abends",
    "pf2e-weather-forge.time.morning": "Morgens",
    "pf2e-weather-forge.time.night": "Nachts",
    "pf2e-weather-forge.time.noon": "Mittags",
    "pf2e-weather-forge.trend.cooler": "kühler",
    "pf2e-weather-forge.trend.stable": "stabil",
    "pf2e-weather-forge.trend.warmer": "wärmer",
    "pf2e-weather-forge.ui.accept": "Vorschau übernehmen",
    "pf2e-weather-forge.ui.allowExtreme": "Extremwetter erlauben",
    "pf2e-weather-forge.ui.calendar": "Calendar Forge",
    "pf2e-weather-forge.ui.climateZone": "Klimazone",
    "pf2e-weather-forge.ui.currentWeather": "Aktuelles Wetter",
    "pf2e-weather-forge.ui.extremeType": "Extremwetterart",
    "pf2e-weather-forge.ui.forceExtreme": "Extremwetter erzwingen",
    "pf2e-weather-forge.ui.generate": "Nächste Tageszeit generieren",
    "pf2e-weather-forge.ui.nextDay": "+1 Tag",
    "pf2e-weather-forge.ui.nextTime": "Nächste Tageszeit",
    "pf2e-weather-forge.ui.noPreview": "Noch keine Vorschau generiert.",
    "pf2e-weather-forge.ui.preview": "Vorschau",
    "pf2e-weather-forge.ui.previousDay": "-1 Tag",
    "pf2e-weather-forge.ui.previousTime": "Vorherige Tageszeit",
    "pf2e-weather-forge.ui.reset": "Zurücksetzen",
    "pf2e-weather-forge.ui.saveCalendar": "Kalender speichern",
    "pf2e-weather-forge.ui.settings": "Einstellungen",
    "pf2e-weather-forge.ui.settingsMovedHint": "Klima, Kalender, Historie und Chat-Ausgabe findest du jetzt im Reiter Einstellungen.",
    "pf2e-weather-forge.ui.weatherGeneration": "Wettergenerierung",
    "pf2e-weather-forge.weekday.fireday": "Feuertag (Freitag)",
    "pf2e-weather-forge.weekday.moonday": "Mondtag (Montag)",
    "pf2e-weather-forge.weekday.oathday": "Schwurtag (Donnerstag)",
    "pf2e-weather-forge.weekday.starday": "Sterntag (Samstag)",
    "pf2e-weather-forge.weekday.sunday": "Sonnentag (Sonntag)",
    "pf2e-weather-forge.weekday.toilday": "Toildag (Dienstag)",
    "pf2e-weather-forge.weekday.wealday": "Wealtag (Mittwoch)",
    "pf2e-weather-forge.windStrength.breeze": "leichte Brise",
    "pf2e-weather-forge.windStrength.calm": "windstill",
    "pf2e-weather-forge.windStrength.strong": "starker Wind",
    "pf2e-weather-forge.windStrength.violent": "stürmisch",
    "pf2e-weather-forge.windStrength.windy": "windig",
    "pf2e-weather-forge.tabs.forecast": "Vorhersage",
    "pf2e-weather-forge.forecast.title": "Wettervorhersage",
    "pf2e-weather-forge.forecast.summaryHint": "Die Vorhersage basiert auf der aktuellen Wetterlage. Später generiertes Wetter orientiert sich daran, kann aber plausibel abweichen.",
    "pf2e-weather-forge.forecast.generate": "Vorhersage aktualisieren",
    "pf2e-weather-forge.forecast.publishGM": "Vorhersage an GM senden",
    "pf2e-weather-forge.forecast.empty": "Noch keine Vorhersage erstellt.",
    "pf2e-weather-forge.forecast.chatTitle": "Wettervorhersage",
    "pf2e-weather-forge.forecast.chatHint": "SL-Information: Die spätere Wettergenerierung orientiert sich an dieser Prognose, ist aber nicht exakt festgeschrieben.",
    "pf2e-weather-forge.forecast.days.label": "Vorhersagezeitraum",
    "pf2e-weather-forge.forecast.days.1": "1 Tag",
    "pf2e-weather-forge.forecast.days.3": "3 Tage",
    "pf2e-weather-forge.forecast.days.5": "5 Tage",
    "pf2e-weather-forge.forecast.days.7": "7 Tage",
    "pf2e-weather-forge.forecast.field.expected": "Erwartung",
    "pf2e-weather-forge.forecast.field.temperatureRange": "Temperaturspanne",
    "pf2e-weather-forge.forecast.field.rainRisk": "Regenrisiko",
    "pf2e-weather-forge.forecast.field.stormRisk": "Gewitterrisiko",
    "pf2e-weather-forge.forecast.field.confidence": "Verlässlichkeit",
    "pf2e-weather-forge.forecast.field.trend": "Trend",
    "pf2e-weather-forge.forecast.field.driver": "Wetterlage",
    "pf2e-weather-forge.forecast.weather.fair": "meist heiter",
    "pf2e-weather-forge.forecast.weather.cloudy": "zunehmend bewölkt",
    "pf2e-weather-forge.forecast.weather.overcast": "bedeckt",
    "pf2e-weather-forge.forecast.weather.rainPossible": "Regen möglich",
    "pf2e-weather-forge.forecast.weather.rainLikely": "Regen wahrscheinlich",
    "pf2e-weather-forge.forecast.weather.stormPossible": "Gewitter möglich",
    "pf2e-weather-forge.forecast.weather.heatwave": "anhaltende Hitze",
    "pf2e-weather-forge.forecast.weather.coldSnap": "Kälteeinbruch",
    "pf2e-weather-forge.forecast.weather.blizzard": "Schneesturm möglich",
    "pf2e-weather-forge.forecast.driver.stableAir": "stabile Luftmasse",
    "pf2e-weather-forge.forecast.driver.highPressure": "Hochdruckgebiet",
    "pf2e-weather-forge.forecast.driver.lowPressure": "Tiefdruckgebiet",
    "pf2e-weather-forge.forecast.driver.coldFront": "Kaltfront",
    "pf2e-weather-forge.forecast.driver.warmFront": "Warmfront",
    "pf2e-weather-forge.forecast.driver.heatwave": "Hitzewelle",
    "pf2e-weather-forge.forecast.driver.coldSnap": "Kältewelle",
    "pf2e-weather-forge.forecast.driver.blizzard": "Schneesturmfront",
    "pf2e-weather-forge.forecast.hint.stableAir": "Die Wetterlage wirkt träge und verändert sich voraussichtlich nur langsam.",
    "pf2e-weather-forge.forecast.hint.highPressure": "Die Luft wirkt trocken und ruhig. Wolken lösen sich eher auf.",
    "pf2e-weather-forge.forecast.hint.lowPressure": "Feuchte Luft sammelt sich. Dichtere Wolken und Regen werden wahrscheinlicher.",
    "pf2e-weather-forge.forecast.hint.coldFront": "Eine kühlere Front nähert sich. Wind, Wolken und Schauer werden wahrscheinlicher.",
    "pf2e-weather-forge.forecast.hint.warmFront": "Mildere Luft zieht auf. Es wird eher feuchter und etwas wärmer.",
    "pf2e-weather-forge.forecast.hint.heatwave": "Die Hitze hält sich in der Region fest. Abkühlung ist vorerst unwahrscheinlich.",
    "pf2e-weather-forge.forecast.hint.coldSnap": "Kalte Luft setzt sich fest. Nächte und Morgenstunden werden spürbar härter.",
    "pf2e-weather-forge.forecast.hint.blizzard": "Schwere Schneewolken und scharfer Wind dominieren die Vorhersage.",
    "pf2e-weather-forge.notification.forecastGenerated": "Wettervorhersage aktualisiert.",
    "pf2e-weather-forge.notification.noForecast": "Es gibt noch keine Wettervorhersage.",
    "pf2e-weather-forge.settings.forecastState.name": "Vorhersagezustand",
    "pf2e-weather-forge.settings.forecastState.hint": "Interne Wettervorhersage der Weather Forge.",
    "pf2e-weather-forge.settings.forecastDays.name": "Vorhersagezeitraum",
    "pf2e-weather-forge.settings.forecastDays.hint": "Anzahl der Tage, die im Vorhersage-Reiter erzeugt werden."
  },
  "en": {
    "pf2e-weather-forge.app.title": "PF2e Weather Forge",
    "pf2e-weather-forge.chat.defaultMode": "Default chat output",
    "pf2e-weather-forge.chat.mode.ask": "Ask when publishing",
    "pf2e-weather-forge.chat.mode.gm": "Whisper to GM",
    "pf2e-weather-forge.chat.mode.public": "Public",
    "pf2e-weather-forge.chat.publishGM": "Send to GM",
    "pf2e-weather-forge.chat.publishPublic": "Send Publicly",
    "pf2e-weather-forge.chat.publishTitle": "Publish Weather",
    "pf2e-weather-forge.chat.speaker": "PF2e Weather Forge",
    "pf2e-weather-forge.chat.title": "Weather Report",
    "pf2e-weather-forge.climate.arctic": "Arctic",
    "pf2e-weather-forge.climate.coastal": "Coastal",
    "pf2e-weather-forge.climate.desert": "Desert",
    "pf2e-weather-forge.climate.magical": "Magically warped",
    "pf2e-weather-forge.climate.mediterranean": "Mediterranean",
    "pf2e-weather-forge.climate.mountain": "Mountain",
    "pf2e-weather-forge.climate.swamp": "Swamp",
    "pf2e-weather-forge.climate.temperate": "Temperate",
    "pf2e-weather-forge.climate.tropical": "Tropical",
    "pf2e-weather-forge.cloudDensity.clear": "clear",
    "pf2e-weather-forge.cloudDensity.cloudy": "cloudy",
    "pf2e-weather-forge.cloudDensity.overcast": "overcast",
    "pf2e-weather-forge.cloudDensity.scattered": "scattered clouds",
    "pf2e-weather-forge.description.clearMild": "The air is calm and pleasant. A serviceable travel day, with no temper from the sky.",
    "pf2e-weather-forge.description.coldClear": "The air is clear and cold. Each breath briefly exists in the world before vanishing.",
    "pf2e-weather-forge.description.extreme.blizzard": "Snow and wind merge into white roaring. Keeping your bearings becomes a die roll against the sky.",
    "pf2e-weather-forge.description.extreme.coldSnap": "A hard cold has sunk its teeth in. Fingers stiffen, breath burns, and even sounds feel brittle.",
    "pf2e-weather-forge.description.extreme.fog": "Dense fog swallows distance and shape. The world ends a few steps ahead.",
    "pf2e-weather-forge.description.extreme.heatwave": "The heat stands in the air like glass. Every movement costs more strength than it should.",
    "pf2e-weather-forge.description.extreme.storm": "A storm rules the area. Gusts tear at everything, rain strikes sideways, and the sky feels like an angry beast.",
    "pf2e-weather-forge.description.heavyRain": "Rain crashes down in heavy sheets. Puddles grow quickly, cloth clings to skin, and armor sounds dull beneath the drops.",
    "pf2e-weather-forge.description.hotClear": "Heat lies heavy over the land. Metal grows unpleasantly warm and shade feels precious.",
    "pf2e-weather-forge.description.lightRain": "Fine rain settles on clothes and roads. The world feels muted, as though sound has been tucked beneath a wet blanket.",
    "pf2e-weather-forge.description.mist": "Low, damp mist hangs in the air and swallows sound like wet felt.",
    "pf2e-weather-forge.description.overcast": "A thick ceiling of cloud hangs over the area. The light is flat and the mood crouches low.",
    "pf2e-weather-forge.description.snow": "Snow falls in cold veils. Steps grow quieter, shapes soften, and the air bites between breaths.",
    "pf2e-weather-forge.description.thunderstorm": "Heavy clouds tower overhead, thunder rolls across the land, and rain lashes down in gusts.",
    "pf2e-weather-forge.description.windy": "The wind tugs at cloaks, hair, and loose straps. Conversations must wrestle with the howl of the gusts.",
    "pf2e-weather-forge.extreme.blizzard": "Blizzard",
    "pf2e-weather-forge.extreme.coldSnap": "Cold snap",
    "pf2e-weather-forge.extreme.fog": "Dense fog",
    "pf2e-weather-forge.extreme.heatwave": "Heatwave",
    "pf2e-weather-forge.extreme.none": "None",
    "pf2e-weather-forge.extreme.storm": "Storm",
    "pf2e-weather-forge.extremePhase.active": "active",
    "pf2e-weather-forge.extremePhase.building": "building",
    "pf2e-weather-forge.extremePhase.fading": "fading",
    "pf2e-weather-forge.field.climateZone": "Climate zone",
    "pf2e-weather-forge.field.cloudDensity": "Cloud density",
    "pf2e-weather-forge.field.dailyMinMax": "Daily min/max",
    "pf2e-weather-forge.field.dayOfMonth": "Day of month",
    "pf2e-weather-forge.field.extremeWeather": "Extreme weather",
    "pf2e-weather-forge.field.humidity": "Humidity",
    "pf2e-weather-forge.field.month": "Month",
    "pf2e-weather-forge.field.moonPhase": "Moon phase",
    "pf2e-weather-forge.field.precipitation": "Precipitation",
    "pf2e-weather-forge.field.temperature": "Temperature",
    "pf2e-weather-forge.field.timeSegment": "Time segment",
    "pf2e-weather-forge.field.trend": "Trend",
    "pf2e-weather-forge.field.weekday": "Weekday",
    "pf2e-weather-forge.field.windStrength": "Wind strength",
    "pf2e-weather-forge.field.year": "Year",
    "pf2e-weather-forge.history.clear": "Clear history",
    "pf2e-weather-forge.history.empty": "No weather history yet. Accept a preview to store the first entry.",
    "pf2e-weather-forge.history.hint": "Stores each accepted weather state by date and time segment. Entries remain fully localizable because keys are stored instead of finished display text.",
    "pf2e-weather-forge.history.noEntries": "No entries",
    "pf2e-weather-forge.history.title": "Weather History",
    "pf2e-weather-forge.humidity.dry": "dry",
    "pf2e-weather-forge.humidity.humid": "humid",
    "pf2e-weather-forge.humidity.normal": "normal",
    "pf2e-weather-forge.humidity.veryHumid": "very humid",
    "pf2e-weather-forge.month.abadius": "Abadius (January)",
    "pf2e-weather-forge.month.arodus": "Arodus (August)",
    "pf2e-weather-forge.month.calistril": "Calistril (February)",
    "pf2e-weather-forge.month.desnus": "Desnus (May)",
    "pf2e-weather-forge.month.erastus": "Erastus (July)",
    "pf2e-weather-forge.month.gozran": "Gozran (April)",
    "pf2e-weather-forge.month.kuthona": "Kuthona (December)",
    "pf2e-weather-forge.month.lamashan": "Lamashan (October)",
    "pf2e-weather-forge.month.neth": "Neth (November)",
    "pf2e-weather-forge.month.pharast": "Pharast (March)",
    "pf2e-weather-forge.month.rova": "Rova (September)",
    "pf2e-weather-forge.month.sarenith": "Sarenith (June)",
    "pf2e-weather-forge.moon.firstQuarter": "First Quarter",
    "pf2e-weather-forge.moon.full": "Full moon",
    "pf2e-weather-forge.moon.fullMoon": "Full Moon",
    "pf2e-weather-forge.moon.lastQuarter": "Last Quarter",
    "pf2e-weather-forge.moon.new": "New moon",
    "pf2e-weather-forge.moon.newMoon": "New Moon",
    "pf2e-weather-forge.moon.waningCrescent": "Waning Crescent",
    "pf2e-weather-forge.moon.waningGibbous": "Waning Gibbous",
    "pf2e-weather-forge.moon.waxingCrescent": "Waxing Crescent",
    "pf2e-weather-forge.moon.waxingGibbous": "Waxing Gibbous",
    "pf2e-weather-forge.notification.calendarSaved": "The internal calendar has been saved.",
    "pf2e-weather-forge.notification.historyCleared": "The weather history has been cleared.",
    "pf2e-weather-forge.notification.settingsSaved": "Settings saved.",
    "pf2e-weather-forge.notification.weatherAccepted": "The weather preview has been accepted.",
    "pf2e-weather-forge.notification.weatherReset": "The weather has been reset for the selected climate zone.",
    "pf2e-weather-forge.precipitation.drizzle": "Drizzle",
    "pf2e-weather-forge.precipitation.heavyRain": "Heavy rain",
    "pf2e-weather-forge.precipitation.lightRain": "Light rain",
    "pf2e-weather-forge.precipitation.mist": "Mist/fog",
    "pf2e-weather-forge.precipitation.none": "No precipitation",
    "pf2e-weather-forge.precipitation.rain": "Rain",
    "pf2e-weather-forge.precipitation.snow": "Snow",
    "pf2e-weather-forge.precipitation.thunderstorm": "Thunderstorm",
    "pf2e-weather-forge.season.autumn": "Autumn",
    "pf2e-weather-forge.season.spring": "Spring",
    "pf2e-weather-forge.season.summer": "Summer",
    "pf2e-weather-forge.season.winter": "Winter",
    "pf2e-weather-forge.settings.allowExtreme.hint": "Controls whether extreme weather may occur randomly during generation.",
    "pf2e-weather-forge.settings.allowExtreme.name": "Allow extreme weather",
    "pf2e-weather-forge.settings.calendarState.hint": "Stores the Weather Forge internal Golarion calendar.",
    "pf2e-weather-forge.settings.calendarState.name": "Calendar state",
    "pf2e-weather-forge.settings.chatOutputMode.hint": "Controls which chat output mode is preselected in the Weather Forge window.",
    "pf2e-weather-forge.settings.chatOutputMode.name": "Chat output mode",
    "pf2e-weather-forge.settings.historyLimit.180": "180 days",
    "pf2e-weather-forge.settings.historyLimit.30": "30 days",
    "pf2e-weather-forge.settings.historyLimit.365": "365 days",
    "pf2e-weather-forge.settings.historyLimit.90": "90 days",
    "pf2e-weather-forge.settings.historyLimit.hint": "Controls how many calendar days are kept in the weather history.",
    "pf2e-weather-forge.settings.historyLimit.name": "History limit",
    "pf2e-weather-forge.settings.historyLimit.unlimited": "Unlimited",
    "pf2e-weather-forge.settings.open.hint": "Opens the PF2e Weather Forge.",
    "pf2e-weather-forge.settings.open.label": "Open",
    "pf2e-weather-forge.settings.open.name": "Open Weather Forge",
    "pf2e-weather-forge.settings.weatherHistory.hint": "Stores accepted weather states for later review.",
    "pf2e-weather-forge.settings.weatherHistory.name": "Weather history",
    "pf2e-weather-forge.settings.weatherPreview.hint": "Stores the current preview before it is accepted.",
    "pf2e-weather-forge.settings.weatherPreview.name": "Weather Preview",
    "pf2e-weather-forge.settings.weatherState.hint": "Stores the world's current weather.",
    "pf2e-weather-forge.settings.weatherState.name": "Weather State",
    "pf2e-weather-forge.settingsTab.calendarTitle": "Calendar",
    "pf2e-weather-forge.settingsTab.climateTitle": "Climate & Extreme Weather",
    "pf2e-weather-forge.settingsTab.outputTitle": "History & Chat",
    "pf2e-weather-forge.settingsTab.save": "Save Settings",
    "pf2e-weather-forge.tabs.generator": "Weather Generation",
    "pf2e-weather-forge.tabs.history": "Weather History",
    "pf2e-weather-forge.tabs.label": "PF2e Weather Forge tabs",
    "pf2e-weather-forge.tabs.settings": "Settings",
    "pf2e-weather-forge.time.afternoon": "Afternoon",
    "pf2e-weather-forge.time.evening": "Evening",
    "pf2e-weather-forge.time.morning": "Morning",
    "pf2e-weather-forge.time.night": "Night",
    "pf2e-weather-forge.time.noon": "Noon",
    "pf2e-weather-forge.trend.cooler": "cooler",
    "pf2e-weather-forge.trend.stable": "stable",
    "pf2e-weather-forge.trend.warmer": "warmer",
    "pf2e-weather-forge.ui.accept": "Accept preview",
    "pf2e-weather-forge.ui.allowExtreme": "Allow extreme weather",
    "pf2e-weather-forge.ui.calendar": "Calendar Forge",
    "pf2e-weather-forge.ui.climateZone": "Climate Zone",
    "pf2e-weather-forge.ui.currentWeather": "Current Weather",
    "pf2e-weather-forge.ui.extremeType": "Extreme weather type",
    "pf2e-weather-forge.ui.forceExtreme": "Force extreme weather",
    "pf2e-weather-forge.ui.generate": "Generate next time segment",
    "pf2e-weather-forge.ui.nextDay": "+1 day",
    "pf2e-weather-forge.ui.nextTime": "Next time segment",
    "pf2e-weather-forge.ui.noPreview": "No preview generated yet.",
    "pf2e-weather-forge.ui.preview": "Preview",
    "pf2e-weather-forge.ui.previousDay": "-1 day",
    "pf2e-weather-forge.ui.previousTime": "Previous time segment",
    "pf2e-weather-forge.ui.reset": "Reset",
    "pf2e-weather-forge.ui.saveCalendar": "Save calendar",
    "pf2e-weather-forge.ui.settings": "Settings",
    "pf2e-weather-forge.ui.settingsMovedHint": "Climate, calendar, history, and chat output now live in the Settings tab.",
    "pf2e-weather-forge.ui.weatherGeneration": "Weather generation",
    "pf2e-weather-forge.weekday.fireday": "Fireday (Friday)",
    "pf2e-weather-forge.weekday.moonday": "Moonday (Monday)",
    "pf2e-weather-forge.weekday.oathday": "Oathday (Thursday)",
    "pf2e-weather-forge.weekday.starday": "Starday (Saturday)",
    "pf2e-weather-forge.weekday.sunday": "Sunday (Sunday)",
    "pf2e-weather-forge.weekday.toilday": "Toilday (Tuesday)",
    "pf2e-weather-forge.weekday.wealday": "Wealday (Wednesday)",
    "pf2e-weather-forge.windStrength.breeze": "light breeze",
    "pf2e-weather-forge.windStrength.calm": "calm",
    "pf2e-weather-forge.windStrength.strong": "strong wind",
    "pf2e-weather-forge.windStrength.violent": "violent wind",
    "pf2e-weather-forge.windStrength.windy": "windy",
    "pf2e-weather-forge.tabs.forecast": "Forecast",
    "pf2e-weather-forge.forecast.title": "Weather Forecast",
    "pf2e-weather-forge.forecast.summaryHint": "The forecast is based on the current weather pattern. Future generated weather follows it, but may plausibly differ.",
    "pf2e-weather-forge.forecast.generate": "Update Forecast",
    "pf2e-weather-forge.forecast.publishGM": "Send Forecast to GM",
    "pf2e-weather-forge.forecast.empty": "No forecast has been created yet.",
    "pf2e-weather-forge.forecast.chatTitle": "Weather Forecast",
    "pf2e-weather-forge.forecast.chatHint": "GM information: future weather generation follows this forecast, but is not locked to it exactly.",
    "pf2e-weather-forge.forecast.days.label": "Forecast Range",
    "pf2e-weather-forge.forecast.days.1": "1 day",
    "pf2e-weather-forge.forecast.days.3": "3 days",
    "pf2e-weather-forge.forecast.days.5": "5 days",
    "pf2e-weather-forge.forecast.days.7": "7 days",
    "pf2e-weather-forge.forecast.field.expected": "Expected",
    "pf2e-weather-forge.forecast.field.temperatureRange": "Temperature range",
    "pf2e-weather-forge.forecast.field.rainRisk": "Rain risk",
    "pf2e-weather-forge.forecast.field.stormRisk": "Storm risk",
    "pf2e-weather-forge.forecast.field.confidence": "Confidence",
    "pf2e-weather-forge.forecast.field.trend": "Trend",
    "pf2e-weather-forge.forecast.field.driver": "Weather pattern",
    "pf2e-weather-forge.forecast.weather.fair": "mostly fair",
    "pf2e-weather-forge.forecast.weather.cloudy": "increasing clouds",
    "pf2e-weather-forge.forecast.weather.overcast": "overcast",
    "pf2e-weather-forge.forecast.weather.rainPossible": "rain possible",
    "pf2e-weather-forge.forecast.weather.rainLikely": "rain likely",
    "pf2e-weather-forge.forecast.weather.stormPossible": "storms possible",
    "pf2e-weather-forge.forecast.weather.heatwave": "persistent heat",
    "pf2e-weather-forge.forecast.weather.coldSnap": "cold snap",
    "pf2e-weather-forge.forecast.weather.blizzard": "blizzard possible",
    "pf2e-weather-forge.forecast.driver.stableAir": "stable air mass",
    "pf2e-weather-forge.forecast.driver.highPressure": "high pressure",
    "pf2e-weather-forge.forecast.driver.lowPressure": "low pressure",
    "pf2e-weather-forge.forecast.driver.coldFront": "cold front",
    "pf2e-weather-forge.forecast.driver.warmFront": "warm front",
    "pf2e-weather-forge.forecast.driver.heatwave": "heatwave",
    "pf2e-weather-forge.forecast.driver.coldSnap": "cold wave",
    "pf2e-weather-forge.forecast.driver.blizzard": "blizzard front",
    "pf2e-weather-forge.forecast.hint.stableAir": "The weather pattern is sluggish and should change only slowly.",
    "pf2e-weather-forge.forecast.hint.highPressure": "The air feels dry and calm. Clouds are more likely to break.",
    "pf2e-weather-forge.forecast.hint.lowPressure": "Moist air is gathering. Denser clouds and rain become more likely.",
    "pf2e-weather-forge.forecast.hint.coldFront": "A cooler front approaches. Wind, clouds, and showers become more likely.",
    "pf2e-weather-forge.forecast.hint.warmFront": "Milder air is moving in. Conditions become more humid and slightly warmer.",
    "pf2e-weather-forge.forecast.hint.heatwave": "The heat is holding over the region. Relief is unlikely for now.",
    "pf2e-weather-forge.forecast.hint.coldSnap": "Cold air settles in. Nights and mornings grow noticeably harsher.",
    "pf2e-weather-forge.forecast.hint.blizzard": "Heavy snow clouds and sharp winds dominate the forecast.",
    "pf2e-weather-forge.notification.forecastGenerated": "Weather forecast updated.",
    "pf2e-weather-forge.notification.noForecast": "There is no weather forecast yet.",
    "pf2e-weather-forge.settings.forecastState.name": "Forecast state",
    "pf2e-weather-forge.settings.forecastState.hint": "Internal Weather Forge forecast state.",
    "pf2e-weather-forge.settings.forecastDays.name": "Forecast range",
    "pf2e-weather-forge.settings.forecastDays.hint": "Number of days generated in the Forecast tab."
  }
};



// Calendar Forge integration strings were added after the original fallback table.
// Keep a compact second layer here so ApplicationV2 stays readable even when Foundry's
// package language cache has not picked up a newly-added module language key yet.
const WEATHER_FORGE_INTEGRATION_TRANSLATIONS = {
  de: {
    "pf2e-weather-forge.calendarIntegration.title": "Calendar-Forge-Integration",
    "pf2e-weather-forge.calendarIntegration.sourceLabel": "Kalenderquelle",
    "pf2e-weather-forge.calendarIntegration.region": "Calendar-Forge-Region",
    "pf2e-weather-forge.calendarIntegration.moon": "Mond für Weather Forge",
    "pf2e-weather-forge.calendarIntegration.mode": "Wetterwechsel bei neuer Tagesphase",
    "pf2e-weather-forge.calendarIntegration.dayparts": "Beginn der Tagesphasen",
    "pf2e-weather-forge.calendarIntegration.active": "Calendar Forge aktiv",
    "pf2e-weather-forge.calendarIntegration.fallback": "Interner Kalender als Fallback",
    "pf2e-weather-forge.calendarIntegration.currentOpen": "Wetter für diese Tagesphase noch offen",
    "pf2e-weather-forge.calendarIntegration.currentResolved": "Wetter für diese Tagesphase festgelegt",
    "pf2e-weather-forge.calendarIntegration.prepareNext": "Nächste Tagesphase vorbereiten",
    "pf2e-weather-forge.calendarIntegration.nextPrepared": "Vorschau für die nächste Tagesphase vorbereitet",
    "pf2e-weather-forge.calendarIntegration.nextPhase": "Nächste Tagesphase",
    "pf2e-weather-forge.calendarIntegration.previewCurrent": "Vorschau für die aktuelle Tagesphase",
    "pf2e-weather-forge.calendarIntegration.previewNext": "Vorschau für die nächste Tagesphase",
    "pf2e-weather-forge.calendarIntegration.noCurrentPreview": "Noch keine Vorschau für die aktuelle Tagesphase generiert.",
    "pf2e-weather-forge.calendarIntegration.noNextPreview": "Noch keine Vorschau für die nächste Tagesphase vorbereitet.",
    "pf2e-weather-forge.calendarIntegration.queuedHint": "Diese Vorschau ist vorbereitet und wird erst beim Erreichen der nächsten Tagesphase zum aktuellen Wetterkandidaten.",
    "pf2e-weather-forge.calendarIntegration.timeOwned": "Datum und Uhrzeit kommen aus Calendar Forge. Weather Forge verändert die Weltzeit in diesem Modus nicht.",
    "pf2e-weather-forge.calendarIntegration.source.auto": "Automatisch",
    "pf2e-weather-forge.calendarIntegration.source.calendarForge": "Calendar Forge",
    "pf2e-weather-forge.calendarIntegration.source.internal": "Interner Kalender",
    "pf2e-weather-forge.calendarIntegration.defaultRegion": "Weltstandard / Standardregion",
    "pf2e-weather-forge.calendarIntegration.defaultMoon": "Erster verfügbarer Mond",
    "pf2e-weather-forge.calendarIntegration.automation.manual": "Manuell für die aktuelle Phase",
    "pf2e-weather-forge.calendarIntegration.automation.automatic": "Vollautomatisch",
    "pf2e-weather-forge.settings.calendarSourceMode.name": "Kalenderquelle",
    "pf2e-weather-forge.settings.calendarSourceMode.hint": "Verwendet Calendar Forge, wenn verfügbar, oder den bisherigen internen Kalender als Fallback.",
    "pf2e-weather-forge.settings.calendarForgeRegionId.name": "Calendar-Forge-Region",
    "pf2e-weather-forge.settings.calendarForgeRegionId.hint": "Region, aus der Datum, Jahreszeit und lokale Uhrzeit gelesen werden.",
    "pf2e-weather-forge.settings.calendarForgeMoonId.name": "Weather-Forge-Mond",
    "pf2e-weather-forge.settings.calendarForgeMoonId.hint": "Mond, dessen Phase Weather Forge verwendet. Leer bedeutet erster verfügbarer Mond.",
    "pf2e-weather-forge.settings.daypartAutomationMode.name": "Tagesphasen-Automatik",
    "pf2e-weather-forge.settings.daypartAutomationMode.hint": "Legt fest, ob die aktuell erreichte Tagesphase manuell oder automatisch aufgelöst wird.",
    "pf2e-weather-forge.settings.daypartBoundaries.name": "Tagesphasengrenzen",
    "pf2e-weather-forge.settings.daypartBoundaries.hint": "Lokale Stunden, ab denen Morgen, Mittag, Nachmittag, Abend und Nacht beginnen.",
    "pf2e-weather-forge.settings.calendarDrivenState.name": "Calendar-Forge-Laufzeitstatus",
    "pf2e-weather-forge.settings.calendarDrivenState.hint": "Interner Status für phasenweise Wettersimulation entlang der Foundry-Weltzeit.",
    "pf2e-weather-forge.notification.daypartReached": "Neue Tagesphase erreicht: {daypart}. Das Wetter für diese Phase kann jetzt erzeugt werden.",
    "pf2e-weather-forge.notification.nextPreviewPrepared": "Vorschau für die nächste Tagesphase wurde vorbereitet.",
    "pf2e-weather-forge.notification.calendarTimeRewound": "Die Weltzeit wurde zurückgesetzt. Das aktuelle Wetter bleibt bestehen und wurde auf die neue Tagesphase übertragen.",
    "pf2e-weather-forge.notification.calendarIntegrationError": "Die Calendar-Forge-Wetterintegration konnte die Zeitänderung nicht verarbeiten. Weather Forge bleibt auf dem letzten Wetterzustand.",
    "pf2e-weather-forge.notification.currentPreviewStale": "Die Wettervorschau für die aktuelle Tagesphase wurde verworfen, weil sich Kalenderkontext oder Tagesphase inzwischen geändert haben.",
    "pf2e-weather-forge.notification.queuedPreviewStale": "Die vorbereitete Vorschau für die nächste Tagesphase wurde verworfen, weil sich das Ausgangswetter oder der Kalenderkontext geändert hat.",
    "pf2e-weather-forge.notification.catchupLimit": "Der Zeitsprung überschreitet die sichere Catch-up-Grenze der Weather Forge. Das Wetter wurde nicht teilweise fortgeschrieben; verwende einen kleineren Zeitsprung oder setze das aktuelle Wetter neu.",
    "pf2e-weather-forge.cityIntegration.title": "City-Forge-Kontext",
    "pf2e-weather-forge.cityIntegration.sourceLabel": "Klimaquelle",
    "pf2e-weather-forge.cityIntegration.settlement": "City-Forge-Siedlung",
    "pf2e-weather-forge.cityIntegration.selectSettlement": "Siedlung auswählen …",
    "pf2e-weather-forge.cityIntegration.settlementHint": "Die Auswahl einer Siedlung aktiviert automatisch die Klimaquelle „City-Forge-Siedlung“.",
    "pf2e-weather-forge.cityIntegration.activeContext": "Aktiver Ortskontext",
    "pf2e-weather-forge.cityIntegration.effectiveClimate": "Effektives Weather-Forge-Klima",
    "pf2e-weather-forge.cityIntegration.cityClimate": "City-Forge-Klima",
    "pf2e-weather-forge.cityIntegration.cityTerrain": "Terrain",
    "pf2e-weather-forge.cityIntegration.cityRegion": "Region",
    "pf2e-weather-forge.cityIntegration.manualFallback": "Manuelles / Fallback-Klima",
    "pf2e-weather-forge.cityIntegration.currentWeatherSource": "Erzeugt für",
    "pf2e-weather-forge.cityIntegration.currentMismatch": "Das aktuelle Wetter stammt aus einem anderen City-Forge-Ortskontext. Eine neue Generierung verwendet den jetzt aktiven Kontext.",
    "pf2e-weather-forge.cityIntegration.status.manual": "Manuelles Klima",
    "pf2e-weather-forge.cityIntegration.status.unavailable": "City Forge nicht verfügbar",
    "pf2e-weather-forge.cityIntegration.status.noScene": "Keine aktive Scene",
    "pf2e-weather-forge.cityIntegration.status.unlinked": "Aktive Scene ist keiner City-Forge-Siedlung zugeordnet",
    "pf2e-weather-forge.cityIntegration.status.settlementUnselected": "Keine City-Forge-Siedlung ausgewählt",
    "pf2e-weather-forge.cityIntegration.status.settlementNotFound": "Ausgewählte City-Forge-Siedlung nicht gefunden",
    "pf2e-weather-forge.cityIntegration.status.unmapped": "City-Forge-Klima konnte nicht eindeutig zugeordnet werden",
    "pf2e-weather-forge.cityIntegration.status.city": "City Forge aktiv",
    "pf2e-weather-forge.cityIntegration.source.auto": "Automatisch: City Forge, sonst Fallback",
    "pf2e-weather-forge.cityIntegration.source.scene": "Automatisch über aktive Scene",
    "pf2e-weather-forge.cityIntegration.source.settlement": "City-Forge-Siedlung",
    "pf2e-weather-forge.cityIntegration.source.manual": "Manuell",
    "pf2e-weather-forge.settings.climateSourceMode.name": "Klimaquelle",
    "pf2e-weather-forge.settings.climateSourceMode.hint": "Verwendet bei einer verknüpften aktiven Scene automatisch den City-Forge-Klimakontext oder das manuelle Fallback-Klima.",
    "pf2e-weather-forge.settings.cityForgeSettlementId.name": "City-Forge-Siedlung",
    "pf2e-weather-forge.settings.cityForgeSettlementId.hint": "Explizit ausgewählte City-Forge-Siedlung für die Klimaquelle „City-Forge-Siedlung“.",
    "pf2e-weather-forge.settings.manualClimateZone.name": "Manuelles / Fallback-Klima",
    "pf2e-weather-forge.settings.manualClimateZone.hint": "Klimazone für den manuellen Modus oder wenn kein eindeutiger City-Forge-Klimakontext vorliegt.",
    "pf2e-weather-forge.settings.cityForgeIntegrationState.name": "City-Forge-Integrationsstatus",
    "pf2e-weather-forge.settings.cityForgeIntegrationState.hint": "Interner Migrationsstatus der optionalen City-Forge-Klimaintegration."
  },
  en: {
    "pf2e-weather-forge.calendarIntegration.title": "Calendar Forge Integration",
    "pf2e-weather-forge.calendarIntegration.sourceLabel": "Calendar source",
    "pf2e-weather-forge.calendarIntegration.region": "Calendar Forge region",
    "pf2e-weather-forge.calendarIntegration.moon": "Moon used by Weather Forge",
    "pf2e-weather-forge.calendarIntegration.mode": "Weather change on a new daypart",
    "pf2e-weather-forge.calendarIntegration.dayparts": "Daypart start times",
    "pf2e-weather-forge.calendarIntegration.active": "Calendar Forge active",
    "pf2e-weather-forge.calendarIntegration.fallback": "Internal calendar fallback",
    "pf2e-weather-forge.calendarIntegration.currentOpen": "Weather for this daypart is still unresolved",
    "pf2e-weather-forge.calendarIntegration.currentResolved": "Weather for this daypart is resolved",
    "pf2e-weather-forge.calendarIntegration.prepareNext": "Prepare next daypart",
    "pf2e-weather-forge.calendarIntegration.nextPrepared": "Preview for the next daypart is prepared",
    "pf2e-weather-forge.calendarIntegration.nextPhase": "Next daypart",
    "pf2e-weather-forge.calendarIntegration.previewCurrent": "Preview for the current daypart",
    "pf2e-weather-forge.calendarIntegration.previewNext": "Preview for the next daypart",
    "pf2e-weather-forge.calendarIntegration.noCurrentPreview": "No preview has been generated for the current daypart yet.",
    "pf2e-weather-forge.calendarIntegration.noNextPreview": "No preview has been prepared for the next daypart yet.",
    "pf2e-weather-forge.calendarIntegration.queuedHint": "This preview is prepared and becomes the current weather candidate when the next daypart is reached.",
    "pf2e-weather-forge.calendarIntegration.timeOwned": "Date and time come from Calendar Forge. Weather Forge does not advance world time in this mode.",
    "pf2e-weather-forge.calendarIntegration.source.auto": "Automatic",
    "pf2e-weather-forge.calendarIntegration.source.calendarForge": "Calendar Forge",
    "pf2e-weather-forge.calendarIntegration.source.internal": "Internal calendar",
    "pf2e-weather-forge.calendarIntegration.defaultRegion": "World default / default region",
    "pf2e-weather-forge.calendarIntegration.defaultMoon": "First available moon",
    "pf2e-weather-forge.calendarIntegration.automation.manual": "Manual for current daypart",
    "pf2e-weather-forge.calendarIntegration.automation.automatic": "Fully automatic",
    "pf2e-weather-forge.settings.calendarSourceMode.name": "Calendar source",
    "pf2e-weather-forge.settings.calendarSourceMode.hint": "Uses Calendar Forge when available, otherwise keeps the existing internal calendar as a fallback.",
    "pf2e-weather-forge.settings.calendarForgeRegionId.name": "Calendar Forge region",
    "pf2e-weather-forge.settings.calendarForgeRegionId.hint": "Region from which date, season, and local clock time are read.",
    "pf2e-weather-forge.settings.calendarForgeMoonId.name": "Weather Forge moon",
    "pf2e-weather-forge.settings.calendarForgeMoonId.hint": "Moon phase Weather Forge uses. Empty means the first available moon.",
    "pf2e-weather-forge.settings.daypartAutomationMode.name": "Daypart automation",
    "pf2e-weather-forge.settings.daypartAutomationMode.hint": "Controls whether the currently reached daypart is resolved manually or automatically.",
    "pf2e-weather-forge.settings.daypartBoundaries.name": "Daypart boundaries",
    "pf2e-weather-forge.settings.daypartBoundaries.hint": "Local hours at which morning, noon, afternoon, evening, and night begin.",
    "pf2e-weather-forge.settings.calendarDrivenState.name": "Calendar Forge runtime state",
    "pf2e-weather-forge.settings.calendarDrivenState.hint": "Internal state for daypart-by-daypart weather simulation along Foundry world time.",
    "pf2e-weather-forge.notification.daypartReached": "New daypart reached: {daypart}. Weather for this daypart can now be generated.",
    "pf2e-weather-forge.notification.nextPreviewPrepared": "Preview for the next daypart has been prepared.",
    "pf2e-weather-forge.notification.calendarTimeRewound": "World time was moved backwards. Current weather was kept and carried into the new daypart.",
    "pf2e-weather-forge.notification.calendarIntegrationError": "Calendar Forge weather integration could not process the time change. Weather Forge kept the last weather state.",
    "pf2e-weather-forge.notification.currentPreviewStale": "The weather preview for the current daypart was discarded because the calendar context or daypart changed.",
    "pf2e-weather-forge.notification.queuedPreviewStale": "The prepared preview for the next daypart was discarded because the source weather or calendar context changed.",
    "pf2e-weather-forge.notification.catchupLimit": "The time jump exceeds Weather Forge's safe catch-up limit. Weather was not partially advanced; use a smaller time jump or reset the current weather.",
    "pf2e-weather-forge.cityIntegration.title": "City Forge Context",
    "pf2e-weather-forge.cityIntegration.sourceLabel": "Climate source",
    "pf2e-weather-forge.cityIntegration.settlement": "City Forge settlement",
    "pf2e-weather-forge.cityIntegration.selectSettlement": "Select settlement …",
    "pf2e-weather-forge.cityIntegration.settlementHint": "Selecting a settlement automatically activates the “City Forge settlement” climate source.",
    "pf2e-weather-forge.cityIntegration.activeContext": "Active place context",
    "pf2e-weather-forge.cityIntegration.effectiveClimate": "Effective Weather Forge climate",
    "pf2e-weather-forge.cityIntegration.cityClimate": "City Forge climate",
    "pf2e-weather-forge.cityIntegration.cityTerrain": "Terrain",
    "pf2e-weather-forge.cityIntegration.cityRegion": "Region",
    "pf2e-weather-forge.cityIntegration.manualFallback": "Manual / fallback climate",
    "pf2e-weather-forge.cityIntegration.currentWeatherSource": "Generated for",
    "pf2e-weather-forge.cityIntegration.currentMismatch": "The current weather was generated for a different City Forge place context. New generation will use the currently active context.",
    "pf2e-weather-forge.cityIntegration.status.manual": "Manual climate",
    "pf2e-weather-forge.cityIntegration.status.unavailable": "City Forge unavailable",
    "pf2e-weather-forge.cityIntegration.status.noScene": "No active Scene",
    "pf2e-weather-forge.cityIntegration.status.unlinked": "Active Scene is not linked to a City Forge settlement",
    "pf2e-weather-forge.cityIntegration.status.settlementUnselected": "No City Forge settlement selected",
    "pf2e-weather-forge.cityIntegration.status.settlementNotFound": "Selected City Forge settlement not found",
    "pf2e-weather-forge.cityIntegration.status.unmapped": "City Forge climate could not be mapped unambiguously",
    "pf2e-weather-forge.cityIntegration.status.city": "City Forge active",
    "pf2e-weather-forge.cityIntegration.source.auto": "Automatic: City Forge, otherwise fallback",
    "pf2e-weather-forge.cityIntegration.source.scene": "Automatic from active Scene",
    "pf2e-weather-forge.cityIntegration.source.settlement": "City Forge settlement",
    "pf2e-weather-forge.cityIntegration.source.manual": "Manual",
    "pf2e-weather-forge.settings.climateSourceMode.name": "Climate source",
    "pf2e-weather-forge.settings.climateSourceMode.hint": "Automatically uses City Forge climate context for a linked active Scene, otherwise the manual fallback climate.",
    "pf2e-weather-forge.settings.cityForgeSettlementId.name": "City Forge settlement",
    "pf2e-weather-forge.settings.cityForgeSettlementId.hint": "Explicit City Forge settlement used by the “City Forge settlement” climate source.",
    "pf2e-weather-forge.settings.manualClimateZone.name": "Manual / fallback climate",
    "pf2e-weather-forge.settings.manualClimateZone.hint": "Climate zone used in manual mode or when no unambiguous City Forge climate context is available.",
    "pf2e-weather-forge.settings.cityForgeIntegrationState.name": "City Forge integration state",
    "pf2e-weather-forge.settings.cityForgeIntegrationState.hint": "Internal migration state for the optional City Forge climate integration."
  }
};

function weatherForgeFallbackDictionary() {
  const lang = game?.i18n?.lang ?? "en";
  const primary = WEATHER_FORGE_TRANSLATIONS[lang]
    ?? WEATHER_FORGE_TRANSLATIONS[lang?.split("-")?.[0]]
    ?? WEATHER_FORGE_TRANSLATIONS.en
    ?? {};
  const integration = WEATHER_FORGE_INTEGRATION_TRANSLATIONS[lang]
    ?? WEATHER_FORGE_INTEGRATION_TRANSLATIONS[lang?.split("-")?.[0]]
    ?? WEATHER_FORGE_INTEGRATION_TRANSLATIONS.en
    ?? {};
  return { ...primary, ...integration };
}

export function installWeatherForgeLocalizationFallback(moduleId) {
  // Foundry V14 exposes parts of Localization (notably `format`) as read-only.
  // Never monkey-patch game.i18n here. Keep the fallback available through
  // module-local helpers instead, so package localization remains compatible
  // with current and future Foundry localization implementations.
  return Object.freeze({
    localize: key => weatherForgeLocalize(moduleId, key),
    format: (key, data = {}) => weatherForgeFormat(moduleId, key, data)
  });
}

export function weatherForgeLocalize(moduleId, key) {
  const rawKey = String(key ?? "");
  const dictionary = weatherForgeFallbackDictionary();

  const foundryLocalized = game?.i18n?.localize?.(rawKey);
  if (foundryLocalized && foundryLocalized !== rawKey) return foundryLocalized;

  if (!rawKey.startsWith(moduleId)) return rawKey;
  return dictionary[rawKey] ?? WEATHER_FORGE_INTEGRATION_TRANSLATIONS.en?.[rawKey] ?? WEATHER_FORGE_TRANSLATIONS.en?.[rawKey] ?? rawKey;
}

export function weatherForgeFormat(moduleId, key, data = {}) {
  let template = weatherForgeLocalize(moduleId, key);
  for (const [placeholder, value] of Object.entries(data ?? {})) {
    template = template.replaceAll(`{${placeholder}}`, String(value));
  }
  return template;
}
